# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /transfer/Albert2022/2022/ase-assignment-AlbertTM8

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /transfer/Albert2022/2022/ase-assignment-AlbertTM8

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /transfer/Albert2022/2022/ase-assignment-AlbertTM8/CMakeFiles /transfer/Albert2022/2022/ase-assignment-AlbertTM8//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /transfer/Albert2022/2022/ase-assignment-AlbertTM8/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CurveNet

# Build rule for target.
CurveNet: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CurveNet
.PHONY : CurveNet

# fast build rule for target.
CurveNet/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurveNet.dir/build.make CMakeFiles/CurveNet.dir/build
.PHONY : CurveNet/fast

#=============================================================================
# Target rules for targets named MathTest

# Build rule for target.
MathTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MathTest
.PHONY : MathTest

# fast build rule for target.
MathTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathTest.dir/build.make CMakeFiles/MathTest.dir/build
.PHONY : MathTest/fast

#=============================================================================
# Target rules for targets named CurveNet_autogen

# Build rule for target.
CurveNet_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CurveNet_autogen
.PHONY : CurveNet_autogen

# fast build rule for target.
CurveNet_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurveNet_autogen.dir/build.make CMakeFiles/CurveNet_autogen.dir/build
.PHONY : CurveNet_autogen/fast

#=============================================================================
# Target rules for targets named MathTest_autogen

# Build rule for target.
MathTest_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MathTest_autogen
.PHONY : MathTest_autogen

# fast build rule for target.
MathTest_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathTest_autogen.dir/build.make CMakeFiles/MathTest_autogen.dir/build
.PHONY : MathTest_autogen/fast

CurveNet_autogen/mocs_compilation.o: CurveNet_autogen/mocs_compilation.cpp.o
.PHONY : CurveNet_autogen/mocs_compilation.o

# target to build an object file
CurveNet_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurveNet.dir/build.make CMakeFiles/CurveNet.dir/CurveNet_autogen/mocs_compilation.cpp.o
.PHONY : CurveNet_autogen/mocs_compilation.cpp.o

CurveNet_autogen/mocs_compilation.i: CurveNet_autogen/mocs_compilation.cpp.i
.PHONY : CurveNet_autogen/mocs_compilation.i

# target to preprocess a source file
CurveNet_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurveNet.dir/build.make CMakeFiles/CurveNet.dir/CurveNet_autogen/mocs_compilation.cpp.i
.PHONY : CurveNet_autogen/mocs_compilation.cpp.i

CurveNet_autogen/mocs_compilation.s: CurveNet_autogen/mocs_compilation.cpp.s
.PHONY : CurveNet_autogen/mocs_compilation.s

# target to generate assembly for a file
CurveNet_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurveNet.dir/build.make CMakeFiles/CurveNet.dir/CurveNet_autogen/mocs_compilation.cpp.s
.PHONY : CurveNet_autogen/mocs_compilation.cpp.s

MathTest_autogen/mocs_compilation.o: MathTest_autogen/mocs_compilation.cpp.o
.PHONY : MathTest_autogen/mocs_compilation.o

# target to build an object file
MathTest_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathTest.dir/build.make CMakeFiles/MathTest.dir/MathTest_autogen/mocs_compilation.cpp.o
.PHONY : MathTest_autogen/mocs_compilation.cpp.o

MathTest_autogen/mocs_compilation.i: MathTest_autogen/mocs_compilation.cpp.i
.PHONY : MathTest_autogen/mocs_compilation.i

# target to preprocess a source file
MathTest_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathTest.dir/build.make CMakeFiles/MathTest.dir/MathTest_autogen/mocs_compilation.cpp.i
.PHONY : MathTest_autogen/mocs_compilation.cpp.i

MathTest_autogen/mocs_compilation.s: MathTest_autogen/mocs_compilation.cpp.s
.PHONY : MathTest_autogen/mocs_compilation.s

# target to generate assembly for a file
MathTest_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathTest.dir/build.make CMakeFiles/MathTest.dir/MathTest_autogen/mocs_compilation.cpp.s
.PHONY : MathTest_autogen/mocs_compilation.cpp.s

src/Curve.o: src/Curve.cpp.o
.PHONY : src/Curve.o

# target to build an object file
src/Curve.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurveNet.dir/build.make CMakeFiles/CurveNet.dir/src/Curve.cpp.o
.PHONY : src/Curve.cpp.o

src/Curve.i: src/Curve.cpp.i
.PHONY : src/Curve.i

# target to preprocess a source file
src/Curve.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurveNet.dir/build.make CMakeFiles/CurveNet.dir/src/Curve.cpp.i
.PHONY : src/Curve.cpp.i

src/Curve.s: src/Curve.cpp.s
.PHONY : src/Curve.s

# target to generate assembly for a file
src/Curve.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurveNet.dir/build.make CMakeFiles/CurveNet.dir/src/Curve.cpp.s
.PHONY : src/Curve.cpp.s

src/Intersection.o: src/Intersection.cpp.o
.PHONY : src/Intersection.o

# target to build an object file
src/Intersection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurveNet.dir/build.make CMakeFiles/CurveNet.dir/src/Intersection.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathTest.dir/build.make CMakeFiles/MathTest.dir/src/Intersection.cpp.o
.PHONY : src/Intersection.cpp.o

src/Intersection.i: src/Intersection.cpp.i
.PHONY : src/Intersection.i

# target to preprocess a source file
src/Intersection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurveNet.dir/build.make CMakeFiles/CurveNet.dir/src/Intersection.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathTest.dir/build.make CMakeFiles/MathTest.dir/src/Intersection.cpp.i
.PHONY : src/Intersection.cpp.i

src/Intersection.s: src/Intersection.cpp.s
.PHONY : src/Intersection.s

# target to generate assembly for a file
src/Intersection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurveNet.dir/build.make CMakeFiles/CurveNet.dir/src/Intersection.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathTest.dir/build.make CMakeFiles/MathTest.dir/src/Intersection.cpp.s
.PHONY : src/Intersection.cpp.s

src/NGLScene.o: src/NGLScene.cpp.o
.PHONY : src/NGLScene.o

# target to build an object file
src/NGLScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurveNet.dir/build.make CMakeFiles/CurveNet.dir/src/NGLScene.cpp.o
.PHONY : src/NGLScene.cpp.o

src/NGLScene.i: src/NGLScene.cpp.i
.PHONY : src/NGLScene.i

# target to preprocess a source file
src/NGLScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurveNet.dir/build.make CMakeFiles/CurveNet.dir/src/NGLScene.cpp.i
.PHONY : src/NGLScene.cpp.i

src/NGLScene.s: src/NGLScene.cpp.s
.PHONY : src/NGLScene.s

# target to generate assembly for a file
src/NGLScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurveNet.dir/build.make CMakeFiles/CurveNet.dir/src/NGLScene.cpp.s
.PHONY : src/NGLScene.cpp.s

src/Segment.o: src/Segment.cpp.o
.PHONY : src/Segment.o

# target to build an object file
src/Segment.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurveNet.dir/build.make CMakeFiles/CurveNet.dir/src/Segment.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathTest.dir/build.make CMakeFiles/MathTest.dir/src/Segment.cpp.o
.PHONY : src/Segment.cpp.o

src/Segment.i: src/Segment.cpp.i
.PHONY : src/Segment.i

# target to preprocess a source file
src/Segment.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurveNet.dir/build.make CMakeFiles/CurveNet.dir/src/Segment.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathTest.dir/build.make CMakeFiles/MathTest.dir/src/Segment.cpp.i
.PHONY : src/Segment.cpp.i

src/Segment.s: src/Segment.cpp.s
.PHONY : src/Segment.s

# target to generate assembly for a file
src/Segment.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurveNet.dir/build.make CMakeFiles/CurveNet.dir/src/Segment.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathTest.dir/build.make CMakeFiles/MathTest.dir/src/Segment.cpp.s
.PHONY : src/Segment.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurveNet.dir/build.make CMakeFiles/CurveNet.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurveNet.dir/build.make CMakeFiles/CurveNet.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CurveNet.dir/build.make CMakeFiles/CurveNet.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

tests/Test.o: tests/Test.cpp.o
.PHONY : tests/Test.o

# target to build an object file
tests/Test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathTest.dir/build.make CMakeFiles/MathTest.dir/tests/Test.cpp.o
.PHONY : tests/Test.cpp.o

tests/Test.i: tests/Test.cpp.i
.PHONY : tests/Test.i

# target to preprocess a source file
tests/Test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathTest.dir/build.make CMakeFiles/MathTest.dir/tests/Test.cpp.i
.PHONY : tests/Test.cpp.i

tests/Test.s: tests/Test.cpp.s
.PHONY : tests/Test.s

# target to generate assembly for a file
tests/Test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MathTest.dir/build.make CMakeFiles/MathTest.dir/tests/Test.cpp.s
.PHONY : tests/Test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... CurveNet_autogen"
	@echo "... MathTest_autogen"
	@echo "... CurveNet"
	@echo "... MathTest"
	@echo "... CurveNet_autogen/mocs_compilation.o"
	@echo "... CurveNet_autogen/mocs_compilation.i"
	@echo "... CurveNet_autogen/mocs_compilation.s"
	@echo "... MathTest_autogen/mocs_compilation.o"
	@echo "... MathTest_autogen/mocs_compilation.i"
	@echo "... MathTest_autogen/mocs_compilation.s"
	@echo "... src/Curve.o"
	@echo "... src/Curve.i"
	@echo "... src/Curve.s"
	@echo "... src/Intersection.o"
	@echo "... src/Intersection.i"
	@echo "... src/Intersection.s"
	@echo "... src/NGLScene.o"
	@echo "... src/NGLScene.i"
	@echo "... src/NGLScene.s"
	@echo "... src/Segment.o"
	@echo "... src/Segment.i"
	@echo "... src/Segment.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... tests/Test.o"
	@echo "... tests/Test.i"
	@echo "... tests/Test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

